version: '3.7'
services:
  dbt_container:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/dbt
    environment:
      - REDSHIFT_DBNAME=${REDSHIFT_DBNAME}
      - REDSHIFT_HOST=${REDSHIFT_HOST}
      - REDSHIFT_USERNAME=${REDSHIFT_USERNAME}
      - REDSHIFT_PASSWORD=${REDSHIFT_PASSWORD}
      - REDSHIFT_SCHEMA=${REDSHIFT_SCHEMA}
      - REDSHIFT_PORT=${REDSHIFT_PORT}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL_NAME=${SLACK_CHANNEL_NAME}
      - DBT_PROFILES_DIR=/usr/app/dbt/profiles
    ports:
      - 18080:8080
